# Admissions: 60192
# Bugzilla: 57720
# EMS: 50988
# EOS: 52188
# HCGS: 60049
# HealthWRQS: 60140
# HealthyUNH: 60059
# Housing: 59032
# NCEMRR: 60338
# MedHome: 60036
# NHIHPP: 60141
# NHMAPPER: 59011
# OCM: 58797
# Obliterase: 60023
# RCC: 60130
# RHD_InHall: 58367
# Redmine: 57720
# ResLife: 57996
# SELF: 00000
# SIRS: 58233
# SpiceCore: 59919
# StaffMeetings: 53145
# UACC: 60035
# WJA_AS: 60327
# WJA_DV: 60327
# ePIP: 59333           
* 2012
** July
*** 01
**** WEEKEND
*** 02
**** OCM 
***** 1 hour billable.  Created 'audit log' based on ApplicationLog from EMS (and functions from EPSCOR).
***** 1 hour billable.  Added priors and show priors to arrest form.
****  4 hours non-billable.   Fixes, misc changes.
*** 03
**** OCM
***** 3.5 hours non-billable.  Meeting with Sarah.
***** 1 hours billable. I've updated the Complaint Form to include view/update access checks.  In the Application Log, you'll see the results of these checks.
***** 1 hours non-billable.  Misc. bug fixes.
*** 04
**** HOLIDAY
*** 05
**** VACATION
*** 06
**** VACATION
*** 07
**** WEEKEND
*** 08
**** WEEKEND
*** 09
**** OCM
***** 6 hours non-billable.  Corrected error loading complaint form.  Added lookup of student info by PIDM using using 'Find Student' tool.  Changed listing of violations/sanctions to honor deprecated column.
*** 10
**** OCM
***** 3 hours non-billable.  Changed 'members' fields on resolution tab.  Fixed download.  Removed 'hearing to determine' field.  Printing case number and due date on 'student snapshot'
***** 3 hours bilalble.  Created message areas on dashboads (conduct, arrest, academic).  Imported data from table tcc_tblIncidents to improve lookup of student records.  Import most of the OCM volunteers (most volunteers don't have PIDMs). Switched Res path radioboxes to checkboxes. 
*** 11
**** OCM
***** 3 hours billable.  Added support for "organization" as the respondent for an complaint form.
***** 1 hour billable.  Added support for highlighting of dates customizable by OCM.
***** 2 hours non-billable ot OCM. Misc. bug fixes.
*** 12
**** OCM
***** 1 hour billable.  Completed work on organizations.
***** 1 hour billable.  Updated Sanction Record to store auto complete (using custom script) sancitons.
***** 1 hour billable.  Updated Sanction Record to store hidden on other - ocm report sanctions.
***** 2.5 hours billable.  Updated perl modules to implement privilege checks to limit access as defined by Sarah.
*** 13 
**** OCM
***** 1.5 hours non-billable. Updated OCM menus to implement privilege checks to limit access.
***** 1.5 hours billable.  Created Arrest Dashboard based on Conudct Dashboard.
***** 1 hour billable.  Update Complaint Form hide/show PIDM/Organization fields based on respondent_type.
***** 1 hour billable.  Added notes/files tab to Arrest Form.  Created Arrest Charges record/recordset.  
*** 14
**** WEEKEND
*** 15
**** WEEKEND
*** 16
**** OCM
***** 2 hours non-billable.  Meet with Yunus Syed to work on allowing OCM to lookup PIDM by Student ID via LDAP.  Created perl function to connect to LDAP and obtain PIDM. 
***** 2 hours non-billable.  Corrected perforcemace problems when using Three Strikes report.'
***** 1 hours non-billable.  Misc bug fixes.
***** 1 hours billable.  Updates to Arrest Form letters.
*** 17
**** OCM
***** 1.5 hours billable. Updates to Arrest Form letters.  Added updating Assoc. Deans to Settings page.
***** 2 hours non-billable.  Continued working on LDAP lookup.  At this point, I switched to using a simple shell script to lookup pidm.
***** 1.5 hours non-billable.  Improved Three Strike report (with Phil's help) to improve loading time and its implemention.
*** 18
**** OCM
***** 6.5 hours non-billable.  Using a script created by Bill Costa from UNHIT, I updated OCM to correctly lookup pidm by student id.  Updated ThreeStrikes, Complaint Form and Arrest Form to use access StudentSnapshot using student_id or org_id.  Updated ConductDashboard & ArrestDashboard to allow search for Organziations using Respondent fields.  
*** 19 
**** OCM
***** 4.5 hour non-billable.  Updated ThreeStrikes, Complaint Form and Arrest Form to improve how they access prior data.  Created Arrast Dashbaord.
***** 1 hour billable.  Created recordset 'Conduct with Scholarship'.
*** 20
**** OCM
***** 3 hours billable.  Created Conduct w/Scholarship - Open Cases recordset.  Created ability for OCM staff to switch to hearing officer.
**** RCI
***** 3 hours non-billable.  Created task-output.py to convert task.org into useable data.
*** 21
**** WEEKEND
*** 22
**** WEEKEND
*** 23
**** RCI
***** 3 hour non-billable.  Finished task-output.py to include billable/non-bibllable total and option hanlding.
**** OCM
***** 1.5 hour billable.  Updated MySanctions report to allow complainant to set completed date.
***** .5 hour billable.  Updated Arrest Form for required/optional fields.
***** .5 hour billable.  Updated Open Sanction Reports to ignore complaints with withdrawn sanctions.
***** .5 hour non-billable.  Updated validate_privilege() to allow specifing AND/OR privilege requirement.
*** 24
**** OCM
***** .5 hour non-billable.  Complted changes to validate_privilege().
***** 2 hour non-billable.  Corrected page loading errors.  Updated OCM Privileges document (will send to Blaise tomorrow.)
**** NHMAPPER (59011)
***** 2.5 hours billable.  Updated PDF files from ODT templates for printable output.
*** 25
**** SIRS (58233)
***** 3.5 hours billable.  Help Al debug problems with UserRecord on SIRS website.
**** OCM 
***** 1 hour billable.  Meeting with OCM, VPSAS and RCI.
***** 2 hours non-billable.  Corrected errors Sarah encountered.  Updated OCM Privileges document.
*** 26
**** OCM
***** .5 hour non-billable.  Updated v_ocm_student_snapshot to correctly include/exclude complaints based on business rules from OCM.
***** 2 hour billable.  Imported OCM Arrest data.
**** NHMAPPER (59011)
***** .5 hour billable.  Minor corrections to PDF files.
**** RCI
***** 2 hour non-billable.  Completed task-output.py.  It now supports including task ids both globally and locally.  The output has been updated to include all projects.
**** EMS
***** .5 hour non-billable. Responded to email to paygate-support.
*** 27
**** OCM
***** .5 hour billable.  Imported OCM Arrest data.
***** 2 hours billable.  Imported OCM Arrest data.
***** 2 hours non-billable.  Updated Arrest/Conduct Dashbaords to include counts for acadmeic years.
***** .5 hour non-billable.  Updated student snapshot to use 'not responsible' column.
**** EMS
***** .5 hour non-billable. Responded to email to paygate-support.
*** 28
**** WEEKEND
*** 29
**** WEEKEND
*** 30
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 31
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
** August
*** 01
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 02
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 03
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 04
**** WEEKEND
*** 05
**** WEEKEND
*** 06
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 07
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 08
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 09
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 10
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 11
**** WEEKEND
*** 12
**** WEEKEND
*** 13
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
**** OCM
*** 14
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
**** OCM
*** 15
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
**** OCM
*** 16
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
**** OCM
*** 17
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 18
**** WEEKEND
*** 19
**** WEEKEND
*** 20
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
**** OCM
*** 21
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
**** OCM
*** 22
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 23
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.  OCM Deployed!
*** 24
**** VACATION
*** 25
**** WEEKEND
*** 26
**** WEEKEND
*** 27
**** OCM
***** 3 hours non-billable.  Minor corrections based on feedback from Tyler.
*** 28
**** Housing
***** 1 hour non-billable.  Corrected error when uploading student data feed.  
**** OCM
***** 1 hour non-billable.  Corrected error when cloning a complaint report.
**** ePIP
***** 4.5 hours billable.  Spent time researching/testing automated functional testing tools.  In the end I found these tools: http://watir.com/frameworks/, http://watin.org and http://seleniumhq.org.  My suggestion to aew was Selenium.  It provides a browser-based test cause/test suite creation tool and the option to run tests out side of the browser.
*** 29
**** OCM
***** 4.5 hours non-billable.  Corrections to Arrest Form.
**** Housing
***** .5 hours non-billable.  Corrected issue with upload of students data.
*** 30
**** ePIP
***** 3.5 hours billable.  Spent time learning how to create test cases and test suites with Selenium.  
**** OCM
***** 2.5 hours non-billable.  Corrected issue with OCM reported by Sarah.  Worked to determine cause of error with with OptimalQuery on lithium v. OptimalQuery on housing1.
*** 31
**** OCM
***** 2 hours non-billable.  Meeting with Sarah.
***** 1.5 hours billable.  Added status to three strikes report.  Waiting further information from Sarah.
***** .5 billable.  Added new columns to Complaint List.  Violations (Not Responsible, Responsbile, Pending) and Sanctions types.
***** 2 Corrections/bug fixes to OCM.  Sorting in Dean's Report.  Updated Conduct Tool to only show closed cases, responsbile violations, non-responsbile violations and imposed sanctions.
** September
*** 01
**** WEEKEND
*** 02
**** WEEKEND
*** 03
**** HOLIDAY
*** 04
**** OCM
***** 2 hours non-billable.  Corrected error with respondent auto-complete.  Corrected undefined sub-routine errors. 
**** Housing
***** .5 hour non-billable.  Determine cause of missing freshman student data.  (Data wasn't included in last week's update.  Blaise re-uploaded data.)
**** EMS
***** .5 hour non-billable. Responded to email to paygate-support@sr.unh.edu
**** ePIP
***** .5 hour billable.  Meet with Angela to discuss testing.
*** 05
**** OCM
***** 3 hours billable.  Added complainant proxy to OCM_Uploads.  Updated complainant proxy to complaint form.  This field will allow the user to set a proxy for a given complaint form.
**** ePIP
***** 3 hour billable.  Start of testing process.  Time was spent creating accounts.
*** 08
**** WEEKEND
*** 09
**** WEEKEND
*** 10
**** ePIP
***** 6 hours billable.  Continue work on functionality testing.  Wrote script which tranforms Medicaid data from test plan to selenium test cases.
*** 11
**** ePIP
***** 4 hours billable.  Continued work on functionality testing.  Wrote script which tranforms Needy data from test plan to selenium test cases.
**** UACC
***** 1 hour non-billable.  Helped Allan resolve issue with LDAP access from UACC site on housing1.unh.eud.
**** OCM
***** 1 hour billable.  Added new feature to OCM allowing Sarah to set a custom cell phone number for her volunteers.
*** 12
**** Obliterase 
***** 1 hour non-billable.  Meeting with Tucker, Stephen Wood and myself to discuss work for Stephen's company Obliterase.
***** 1 hour billable.  Updated logo and lCreated favicon.ico.  Updated webserver to use management-console.obliterase.com.
**** ePIP
***** 4 hours billable.  Continued work on functionality testing.
*** 13
**** Obliterase 
***** 2 hours billable.  Updated webserver to use cloud-console.obliterase.com.  Most of the changed requested by Steve Wood have been complted (email sent 09/13/2012 02:39 PM).
**** ePIP
***** 4 hours billable.  Continued work on functionality testing.
*** 14
**** Obliterase 
***** 3 hours billable.  Created footer.  Began work on PDF generation.  Made changes to Device Logs recordset.
**** ePIP
***** 3 hours billable.  Continued work on functionality testing.
*** 15
**** WEEKEND
*** 16
**** WEEKEND
*** 17
**** Obliterase 
***** 4 hours billable.  Created Certificate generation.  Sent Steve an update.  Misc. changes to website.
**** ePIP
***** .5 hour billable.  Closed bugs at aew's request.
**** OCM
***** .5 hour non-billable.  Reviewed whether prior is set correctly all AY1213 complaints.  Sent update to Sarah.
*** 18
**** Bugzilla
***** 1.5 hours non-billable.  Installed bugzilla on zathras to test upgrading our Bugzilla
**** OCM
***** 1 hours non-billable correction/bug fixes.
**** Obliterase
***** 1 hours billable.  Corrected Certificate.
*** 19
**** OCM
***** 5 hours billable.  Templates for Hearing Decision.
**** OCM
***** 1 hours non-billable correction/bug fixes.
*** 20
**** OCM
***** 5 hours billable.  Templates for Hearing Decision.
**** ePIP 
***** 1/2 hour billable.  Rebuliding MMIS.
*** 21
**** VACATION
*** 22
**** WEEKEND
*** 23
**** WEEKEND
*** 24
**** VACATION
*** 25 
**** ePIP 
***** 1 hour billable.  Created summaries of security scan report.  Sent to summary to Even.  Sent another to teh,aew and af.
**** OCM
***** 5 hours billable.  Changes to recent police activity report (removed sentence) and add fields (full name, dob, student id and date the letter was created).  Continued work on hearing decision templates. 
*** 26
**** OCM
***** 3 hours non-billable.  Bug fixes to OCM.  Fixed bug to complaint form which made it impossible to add the same sanction with several sanction types.  Updated complaint form to catch invalid 'release of info requested' data.
***** 3 hours billable.  Loading/saving of sanction templates is now working, along with sanction rationale.
*** 27
**** OCM
***** 3.5 hours billable.  Spent time working on enabling ckeditor support for the rationale text-areas; encountered problems.  I'll revisit this next week.
**** Obliterase
***** .5 hour non-billable.  Removed 'cloud' logo.  Removed NEAT from viewLog script.
**** ResLife
***** 1 hour billable.  Minor updates to Job Description page.
*** 28
**** ePIP
***** 2 hours billable.  Testing and verification of data entered and data reported.
**** HCGS
***** 3 hours billable.  Created website; loaded database from medical-home site.  Removed medical home references from HCGS.  The site is now ready.
**** MEDHOME
***** 1 hours billable.  Reviewed MEDHOME website with Allan.  Spent additional time reference website myself.
*** 29
**** WEEKEND
*** 30
**** WEEKEND

** October
*** 01
**** MedHome
***** 1 hour non-billable.  Meeting with NHIHPP to discuss the project and moving it forward.
**** Obliterase
***** 1.5 hours billable.  Minor updates to website.  Added images above menu.  Added logo to the left of menu.  Added text above menu.
**** HCGS
***** .5 hours billable.  Deployed website to preview server.
**** SpiceCore
***** 2 hours billable.  Setup website on lithium and myxomatosis.
**** HOURS_OWED
***** 1 HOUR OWED
*** 02
**** OCM
***** 2.5 hours non-billable.  Corrected errors with Recent Police Activity report crashing when filtering on 
**** RCC
***** 1 hours non-billable.  Reset AD password; this was done to access maple.unh.edu account.  Reinstalled MS Office.
**** HealthyUNH
***** 2.5 hours non-billable.  Started working on Healthy Fitness map.
*** 03
**** ResLife
***** 1 hour billable.  Minor updates to Welcome page.
**** ePIP 
***** 1 hour billable.  Training on ePIP upload proceedure.
**** HealthyUNH
***** 4 hours non-billable.  Finished working on Healthly Fitness map.  Using jQuery and a jQuery plug-in, jquery.imagemapster to provide a multi-platform UI.
*** 04
**** RCC
***** 4 hour non-billable.  Downtime due to power outage.  Watching of UNH IT Security training videos.
**** Housing
***** 1.5 hour non-billable.  Meeting with Chris, Blaise, Allan and myself to discuss future Housing work.  Created mock-up of inhall-application page using jdmenu.
**** ResLife
***** .5 hour billable.  Deployed latest changes to live site.
*** 05
**** RHD_InHall
***** 1.5 hours non-billable.  Created two other mock-ups using jQuery UI tabs and accordion.  I sent Blaise an email with an update asking him to review them.
**** OCM
***** 1.5 hour non-billable.  Received email from Sarah reporting loss of privileges and cell phone numbers Thursday evening.  After reviewing log and Perl code, I think the problem is related to upload.  I'm waiting on the student feed from back.  Received email from Sarah about incorrect College for student.  After checking database, the issue is incorrect/out-of-day data; emailed Blaise.
**** HealthyUNH
***** 2 hour non-billable.  Minor corrections to map based on feedback from Allan.  Sent email to Stacey and Jo with update.
**** HOURS_OWED
***** 1 HOUR OWED
*** 06
**** WEEKEND
*** 07
**** WEEKEND
*** 08
**** Obliterase
***** 4 hours billable.  Meet with Tucker to discuss updates to system wipe cert.  Completed updates and sent update to Tucker.
**** HealthyUNH
***** 1.5 hour non-billable.  Meeting with Jo, Stacy, Alan and myself to discuss project.  After meeting Allan introducted me to the various NHIHPP staff.
*** 09
**** NHIHPP
***** 5 hours billable.  Created wrapper around shred command line tool.  Sent update to aew.  Tested/researched various system monitor reporting tools (cacti).
*** 10
**** ResLife
***** 2 hours billable.  Updated text (and space) in commitment section in application.  Added new fields to commitment records: commitment title and commitment description.
**** SpiceCore
***** 2 hour billable.  Helped Joe update the DNS record for spicecore.org.  Populated spicecore database with data from waisdivide db.  Updated all perl modules and shtml files to use SPICECORE packages.
**** NHIHPP
***** 2 hour billable.  Tested/researched various system monitor reporting tools (ganglia).
*** 11
**** NHIHPP
***** 1 hours billable.  Updated nshred to print absolute rather than relative path of files.
**** Obliterase
***** 1.5 hour billable.  Added second logo to Obliterase.  I was unable to justify images as Steve Wood requested.  Cleared NEAT logs on database per Tucker request.
**** RHD_InHall
***** 1 hour non-billable.  Reviewed InHall source code to determine quote for RHD InHall assignment work.  Wrote up quote.
**** NHIHPP
***** 2 hour billable.  Tested/researched various system monitor reporting tools (nagios).
*** 12
**** HealthyUNH
***** 3 hours non-billable.  Meeting with Stacey, Jo, Allan and myself to discuss going from prototype to final application.  Wrote up quote as requested.  Sent quote to Jo, Stacy and Jennifer.
**** Housing
***** 1 hour non-billable.  Update and expanded quote from yesterday.
**** NHIHPP
***** 2 hours billable.  Continued and after a simple plain-text report of nshred usage.
**** HCGS
***** .5 hour non-billable.  Started working on quote based on summary of meeting notes from Allan.
*** 13
**** WEEKEND
*** 14
**** WEEKEND
*** 15
**** HCGS
***** .5 hour non-billable.  Meeting with Feseha to discuss project.
**** Obliterase
***** 2 hours billable.  Updates to Obliterase console.
**** UACC
***** 1.5 hours non-billable.  Look into an issue related to access to sign-up for interviews.
*** 16
**** SpiceCore 
***** 1.5 hours billable.  Corrected issues related to login.  Updated Device Logs RS to display ISO images correctly.
**** MedHome
***** 2 hour non-billable.  Meeting with Ashley in regards to issues with uploading of data.  Worked on determining cause of upload errors.
**** HealthWRQS
***** .5 hour non-billable.  Worked on transfering NHIHPP domain to RCI GoDaddy account.
*** 17
**** SpiceCore 
***** 1 hour billable.  Helped Joe setup email forwarding on spicecore.  Created/setup listserv module.
***** .5 hour non-billable.  Corrected/update alias.
**** Obliterase
***** 2.5 hours non-billable.  Worked on determining why the 'Status' column contains unexcpeted results for some log entries.
**** NHIHPP
***** 2 hours non-billable.  Installed and tested nshred util on twilight.  Minor updates to script were required.  Updated report script to support sending end-of-month reports.
*** 18
**** ResLife
***** .5 hour non-billable.  Update allowing withdrawing of incomplete applications.
**** SpiceCore 
***** 1.5 hours billable.  Updates to several perl modules.  Corrected issue with deleting of users.
**** Obliterase
***** 2 hours non-billable.  Tucker and I tracked down the cause of confusion related to the 'Status' column.  Once we determine the cause I updated the DeviceLogs RS to overwrite Status and display Print based on contents of log.
**** HCGS
***** 2 hour billable.  Moved HCGS to git.  Created accounts for Rob, Kelly and Krystalynne.  Fixed issue with ForgotPassword module.
*** 19
**** RCC
***** 1 hour non-billable.  Evaluation with pfm and aew.
**** MedHome
***** .5 hour non-billable.  Conference call to discuss upload issue.
**** HCGS
***** 1 hour non-billable.  Meeting with Feseha, Rob and myself to review/discuss project.
**** HealthyUNH 
***** 1 hour non-billable.  Meeting with Stancy, Sam (from Campus Planning) and myself to discuss the possibility of using a live-feed from campus planning rather than a static map.
*** 20
**** WEEKEND
*** 21
**** WEEKEND
*** 22
**** ResLife
***** 1 hour non-billable.  Created new field, Hiring Term, to store the term the user will be hired for.  
**** HCGS
***** 3.5 hour billable.  Began working on public section of the website based on Feseha's template.
**** SpiceCore 
***** 1.5 hours billable.  Created procmail rules, updated sendmail conf to allow emails to contact@spicecore.org to be re-directed to the spicecore team.
*** 23
**** HCGS
***** 5 hours billable.  Continued working public section of the website.  At this point the menu has been created, the pages have been filled with the content that I have.  HCGS staff will need to enter content for a number of pages.
**** OCM
***** .5 hour non-billable.  Determined cause of permissions errors for Lindsay Furlong.  Linday was entering an invalid date format which caused the INSERT to die.
**** EMS
***** .5 hour non-billable.  Determined solution to request by Admissions. Phil and I determined that used Outlook for mail merge would be better than creating a custom solution.
*** 24
**** OCM
***** 1.5 hours non-billable.  Added column 'extended sanction date' field to sanction reports.  Added column 'complainant' to sanction reports.
**** HCGS
***** 4 hours billable.  Continued working on website.
*** 25
**** OCM
***** 1.5 hours non-billable.  Meeting with Sarah to discuss project, new work and minor bug fixes.
**** HealthyUNH
***** 1.5 hours non-billable.  Using WMS information from Sam, I created a functional openlayers demo.
**** HCGS
***** 3 hours billable.  Copied and updated LOV from EPSCOR.  Created LOVs several times for address and person records.  Added additional fields to person records.  Start working on database schema for sample submission form.
*** 26
**** Housing
***** .5 hour non-billable.  Setup monitor.us for housing1.
**** HCGS
***** 3 hours billable.  Additional improvements to public facing website.  Created (dynamic) breadcrumbs.  Updated all files Feseha will be editing.  Updated preview site.
**** OCM
***** 2 hours non-billable.  Bug fixed. 
*** 27
**** WEEKEND
*** 28
**** WEEKEND
*** 29
**** CURTAILED_OPERATIONS
*** 30
**** CURTAILED_OPERATIONS
*** 31
**** SpiceCore
***** 1.5 hour billable.  Deleted WAIS data from spicecore.org website.
**** OCM
***** 4 hour billable.  Completed two minor billable projects for OCM.  1) Added new move-out dates (this is expandable).  2) Created new tab "Deferred Sanctions".  New privileges and privilege groups were created.
**** Housing
***** .5 hour non-billable.
** November
*** 01
**** EMS
***** .5 hour billable.  Responded to emails to events-dev.
**** HCGS
***** 5.5 hours billable.  Worked on Sample Submission Form/Recordset.
*** 02
**** HCGS
***** 6 hours billable.  Worked on Source Organism Form/Recordset.  Added UNH logo.
*** 03
**** WEEKEND
*** 04
**** WEEKEND
*** 05
**** EMS
***** .5 hour billable.  Responded to emails to events-dev.
**** HCGS
***** .5 hour billable.  Deployed updates to preview site.
**** NHIHPP
***** 3 hour billable.  Created a cpu usage script.
**** ResLife
***** 2 hour non-billable.  Corrected bug with reslife website allowing creation of multiple application.
*** 06
**** HealthyUNH
***** 6 hours billable.  Started working on project.  Created forms/recordsets (based on Fitness Measures) to store fitness locations and its metadata.
*** 07
**** OCM
***** 2 hours non-billable.  Fixed issue with snapshot button on three strikes report.  Corrected incorrect checkbox image.
***** 1.5 hours billable.  Added columns to Complaint Sanctions report.  Added columns to Complaint List report.  Created new recordset.
***** 2 hours billable.  Created links (on conduct dashboard) and recordsets for MoveOut Dates and Alt. Sanction Programs.
**** EMS
***** .5 hour billable.  Responded to emails to events-dev.
*** 08
**** HealthyUNH
***** 3 hours billable.  Continued working on project.
**** OCM
***** 2.5 hours billable.  Created links (on conduct dashboard) and recordsets for MoveOut Dates and Alt. Sanction Programs.
***** .5 hours non-billable.  Tested additional LDAP access.
*** 09
**** HealthyUNH
***** 5.5 hours billable.  Completed working on project.  The map is loading features from database.  The map is displaying a popup for each location from databaes.  The menu is (mostly) working.
**** EMS
***** .5 hour billable.  Responded to emails to events-dev.
*** 10
**** WEEKEND
*** 11
**** WEEKEND
*** 12
**** HOLIDAY
*** 13
**** EMS 
***** .5 hour billable.  Responded to emails to events-dev.
**** OCM
***** .5 hour non-billable.  Created new account on HSNGDB1 for Sarah to access using Crystal Reports.
**** HealthyUNH
***** 5 hour billable.  Continued working on project.
*** 14
**** UACC
***** .5 hour billable.  Minor adjustment to UACC website.
**** EOS 
***** .5 hour billable.  Reviewed log to determine cause of failure to send emails to some people.
**** HealthyUNH
***** 5 hour billable.  Continued working on project.
*** 15
**** Housing
***** 2 hour billable.  Worked on access UNH IT database over VPN.
**** Bugzilla
***** 3 hours non-billable.  Installed bugzilla on new server.
**** EMS
***** .5 hour billable.  Responded to emails to events-dev.
**** Admissions
***** .5 hour billable.  Responded to request via email.
*** 16
**** Admissions
***** 1 hour billable.   Reviewed Admissions Online recordset which has SSN.  Spoke with Jennifer Blosser about this.
**** HealthyUNH
***** 5 hour billable.  Tested site in an iPad.  Minor adjustments to websites based on testing.
*** 17
**** WEEKEND
*** 18 
**** WEEKEND
*** 19
**** HealthyUNH
***** 6 hour billable.  Cleaned up import data.  Added ability to "page" through multiple feature pop-ups.  Added display of all feature pop-ups at a given location.
*** 20
**** HealthyUNH
***** 3.5 hour billable.  Cleaned up import data.  Added ability to "page" through multiple feature pop-ups.  Added display of all feature pop-ups at a given location.
**** OCM
***** 2 hours non-billable.  Meeting with Sarah to review a few outstanding bugs and review hearing decision templates.
**** Admissions
***** .5 hour billable.  Wiped data in admissions database containing SSNs.
*** 21
**** OCM
***** 5 hours non-billable.  Fixed bug in creation of PDF for read-only incidents.  Fixed bug with incident clone feature.  Worked on fixing bugs when adding sanctions to hearing decision (with templates).  Fixed bugs with recordsets for move-out dates and alt. sanction program.  Fixed access checks for move-out dates and alt. sanction program.  Added field to complainant sanction recordset.
**** Admissions
***** .5 hour billable.  Met with Bob and Patrick to discuss wiping of backups contains SSNs.
*** 22
**** HOLIDAY
*** 23
**** HOLIDAY
*** 24
**** WEEKEND
*** 25
**** WEEKEND
*** 26
**** HealthyUNH
***** 6 hour billable.  Cleaned up import data.  Added ability to "page" through multiple feature pop-ups.  Added display of all feature pop-ups at a given location.
*** 27
**** OCM
***** 4 hours non-billable.  Worked to debug a problem when using ckeditor within the hearing decision wizard.
**** HealthyUNH
***** 2 hour billable.  Updated locations, corrected minor bug with display of plus/minus icons.
*** 28
**** VACATION
***** 0 hours billable.  1/2 day.
**** OCM
***** 3 hours non-billable.  Worked to debug a problem when using ckeditor within the hearing decision wizard.
*** 29
**** StaffMeetings 
***** 2 hours non-billable.  Quarterly All Staff Meeting.
**** OCM
***** 3 hours non-billable.  Fixed bug between jWizard and ckeditor.  Wrote and sent update to Sarah.  Wrote email containing description new billable work.
*** 30
**** Housing
***** 3 hour billable.  Worked on accessing ECG database over UNH VPN for Housing-Online.
**** OCM
***** 2 hours non-billable.  Corrected bug when setting completed date.  Updated how violations are saved.
**** Redmine
***** .5 hours non-billable.  Restarted Redmine on kenyan.
** December 
*** 1
**** WEEKEND
*** 2
**** WEEKEND
*** 3
**** NHIHPP
***** 2 hour billable.  Review cpu_by_user data from blackstar.  The current method of using ps to genereate the data is causing high cpu usage.  Creating a binary from python script doesn't help.  Further research leads me to the GNU Accounting Utilities http://www.gnu.org/software/acct/.  I will look into using it to generate the data.
**** HCGS
***** .5 hour non-billable.  Prepared for meeting with Rob.
***** 3 hours billable.  Meet with Rob to discuss the project's status.  We discussed sending an email to the customer to re-connect.  We also discussed how we structure the sample, project and users.
**** EMS
***** .5 hour billable.  Responded to emails to events-dev.
**** ResLife
***** 1 
*** 4
**** HCGS
***** 4 hours billable.  Started writing an email to Feseha Abebe-Akele.  The purpose of this email is to re-connect with HCGS as its been several weeks since I've heard from them.
**** Bugzilla
***** 1.75 hours non-billable.  Fixed problem with the SSL certs for the website hosting our bugzilla server.
**** MedHome
***** .25 hour non-billable.  Updated change the label of the button on this page (http://medical-home.unh.edu/Data/Import).
*** 5
**** MedHome
***** 1 hour non-billable.  Updated query used by Year field on 'Medical Home Data Entry Form'.  Deployed change to preview and live sites.
**** HCGS
***** 1.5 hours billable.  Finish email and send it Feseha Abebe-Akele (and rea).
**** ResLife
***** 3.5 hours non-billable.  Corrected problem with Reslife.  The problem was that Reslife wasn't detecting applications from previous semesters and it wasn't offering to create Returning RA Applications.
*** 6
**** NHIHPP
***** 2.5 hours billable.  Updated cpubyuser.py and cpubyuser-report.py to use data from /var/log/account/pacct (this file is created by the GNU Accounting Utilities http://www.gnu.org/software/acct/).
**** ResLife
***** .5 hour non-billable.  Corrected perl error when switching appfile type.  
***** .5 hour non-billable.   Corrected problem with student not being able to accept RA position offer.  
***** 2.5 hours non-billable.  Corrected several bugs: ResLife wasn't detecting applications previous years (in this case three years) for some students and it wasn't offering to create Returning RA Applications.  When migrating an application from New RA Application to Returning RA Application, ResLife was incorrectly setting the appfile type to 'NEW_RA'.  It should be 'Returning RA'.  This bug has been fixed.    Also, after saving the returning RA application form the student was shown a blank page -- this bug has been fixed.  The student is now shown the just saved application.
*** 7
**** VACATION
*** 8 
**** WEEKEND
*** 9
**** WEEKEND
*** 10
**** HealthyUNH
***** 2.5 hours billable.  Responded to an email from Stacy.  Researched using alternate map layers and using feature collections.
**** HCGS
***** 2.5 hours billable.  Responded to an email from Feseha Abebe-Akele.  Updated LoginOrRegister page.  Added content to People pages for Kelly and Moris from hcgs.unh.edu.
*** 11
**** OCM
***** 1 hour billable.  Updated complaint violations to include additional columns.
**** HealthyUNH
***** .5 hour non-billable.  Corrected bug in menu's display of minus/plus images when opening and closing sub-menus.
*** 12
**** OCM
***** 1 hour billable.  Deployed to the live site the Alternative Sanction Program and Move-Out Date extensions updates.
**** HealthyUNH
***** 1 hour billable.  Sent/Received emails to Campus Planning asking if it possible for them to plan an alternate base layer.  It is this point its not possible but it will be in the future.
***** 3 hours billable.  Continued working on using alternate map base layers.
**** NHIHPP
***** 1.5 billable.  Continued working on cpubyuser/cpubyuser reporting tools.
*** 13
**** StaffMeetings
***** 1.5 hour non-billable.   Farewell lunch for bja.
**** RCC 
***** 1 hour non-billable.  Meeting with aew, bja and myself to review/discuss Bill's projects.
**** HealthyUNH
***** 2 hours billable.  Updated look/style of site based on feedback from Stacey.
**** OCM
***** 1.5 hour billable.  Removed duplicate columns in Complaint Sanctions which aren't filterable.  Added additional columns.
*** 14
**** StaffMeetings
***** 4 hour non-billable.  Research Office division-wide meeting.
**** OCM
***** .5 hour non-billable.  Corrected bug in Conduct Dashboard after pushing updates.
**** HealthyUNH
***** .5 hours non-billable.  Responded to an email from Stacy.
***** 1 hours billable.  Finished updating style.  Updated preview site and sent email to Stacey.
*** 15
**** WEEKEND
*** 16
**** WEEKEND
*** 17
**** NHIHPP
***** 1 hour non-billable.  Meet with aew to discuss the status of the system resources (cpu, memory and hard drive) project.  We researched using disk quota to provide disk usage information.
***** .5 hour billable.  Worked with tjb to setup/enable disk quota functionality on twilight.  At this point, we're waiting on a reboot schedule for Thursday to complete the setup process.
***** 3.5 hour billable.  Updated cpu-usage script to work with Oracle.
***** 1 hour non-billable.  Corrected issue with scripts and the version of python on twilight.
*** 18
**** ResLife
***** .25 hour non-billable.  Enabled sending of emails.  Changed Class and RA AppFiles Report to display all records by default.
**** Housing
***** 1.75 hours non-billable.  Meeting with Blaise, Allan and myself to review remaining work.
***** 2 hours billable.  Updated recordset to include timestamp column and user-selectable filter.  Worked to determine to if v_picked_rooms is correct.
**** HealthyUNH
***** 2 hours billable.  Updated style of feature on map.  Spent time determing the best colors to use based on customer's request.
*** 19
**** OCM
***** 4 hours billable.  Worked on OCM Summary.
**** HCGS
***** 2 hours billable.  Responded to an email from Feseha Abebe-Akele.  Updated LoginOrRegister page.  Added content to People pages for Kelly and Moris from hcgs.unh.edu.
*** 20
**** OCM
***** 5 hours billable.  Worked on OCM Summary.
***** 1 hour non-billable. Updated file notes to replace \x0A (newline) in off-campus address with new-lines.
*** 21
**** VACATION 0 hours billable.  1 day
*** 22 
**** WEEKEND
*** 23
**** WEEKEND
*** 24
**** HOLIDAY
*** 25
**** HOLIDAY
*** 26
**** HOLIDAY
*** 27
**** VACATION 0 hours billable.  1 day
*** 28
**** VACATION 0 hours billable.  1 day
*** 29
**** WEEKEND
*** 30
**** WEEKEND
*** 31
**** VACATION 0 hours billable.  1 day
* 2013
** January
*** 01
**** HOLIDAY
*** 02
**** RCC
***** .5 hour non-billable.  Finished setting up kosh.
**** Housing
***** 4.5 hours billable.  Worked on generation of temporary eligibility codes.  Created pl/sql functions to generate the codes.  Updated UploadTable to set the temproary codes.
***** .5 hour billable.  Continued work on updates to chosen rooms report.
**** WJA_DV
***** .5 hour non-billable.  Spoke with Doug on the phone.  Updated password for opal on foghorn.  Updated user/group for ccg web site on fudd.
*** 03
**** RCC 
***** 1 hour non-billable.  Entered task for December 2012.
**** HCGS
***** 2 hours billable.  Restared work on project.  Begin by making changes based on feedback from HCGS.
**** ResLife
***** 3 hours non-billable.  Corrected a series of bugs reported by Mary.
*** 04
**** SELF
***** 0 hours non-billable.  MISSING HOURS!!!
**** Housing
***** 1.5 hours billable.  Worked on fixing issues with temp. elg. code generation and OCCINFO upload.
*** 05
**** WEEKEND
*** 06 
**** WEEKEND
*** 07
**** ResLife
***** .5 hour non-billable.  Responded to email regarding returning RA uploading their essays.
**** HCGS
***** 5.5 hours billable.  Restared work on project.  Begin by making changes based on feedback from HCGS.
*** 08
**** HCGS
***** 4 hours billable.  Continued working on changes based on feedback from HCGS.
**** NHIHPP
***** 2 hours billable.  Updated cpubyuser.py to handle different output from dump-acct.
*** 09
**** ResLife
***** .25 hours non-billable.  Updated to allow returning RA with status GPA_OK to upload essays.
**** Housing
***** 1.5 hours billable.  Updated temp eligibility codes.  Added checkbox to enable/disable generation of temp codes.
**** NHIHPP
***** 2 hours billable.  Updated cpubyuser.py to handle different output from dump-acct.
**** HCGS
***** 1.5 hours billable.  Began working on the Home page for logged in users.  This page is moddled after the home page from EMS.
**** EOS
***** .75 hour non-billable.  Responded to email regarding an extraneous new-line in message.  I wasn't able to determine the cause.
*** 10
**** HCGS
***** 5 hours billable.  Finished changes based on feedback from HCGS.
*** 11
**** OCM
***** .5 hour non-billable.  Added columns to Complaint list.
**** ResLife
***** .5 hour billable.  Corrected the application date for a few applications which were incorrect.
**** HCGS
***** 1.5 hours non-billable.  Meet with Rob to discuss the project and review any outstanding TODO items.
***** 3.5 hours billable.  Started working on items from my meeting with Rob.
*** 12
**** WEEKEND
*** 13
**** WEEKEND
*** 14
**** StaffMeetings
***** .75 hour non-billable.  Monthly RCC staff meeting.
**** RCC
***** 2.5 hours non-billable.  De-provisioning Bill's Computer Accounts
***** .75 hour non-billable.  Began the process of moving into Bill's office.
**** Housing
***** .5 hour billable.  Updated upload to hold students with holds.  Discussed status of changes with aew.
**** HCGS
***** 1 hour billable.  Updated home with new submission link.  Corrected validiation of sample name.
*** 15
**** StaffMeetings
***** 1 hour non-billable.  Weekly Programming Group meeting.
**** NHIHPP 
***** 1 hour non-billable.  Meeting with Jo, Stacey, Allan and myself to discuss remaining issues with Healthy UNH Meeting Map project. 
*** 16
**** RCC
***** .5 hour non-billable.  Read through Phil's document on RCC Source Revision Control System Standardization.
**** HCGS 
***** 4 hour billable.  Continued work on issues from Meeting.  I hope to have an update ready for Thursday.
**** Housing
***** 1 hour billable.  Updated view used by picked rooms report.  Updated Upload tool to handle students on hold correctly.
*** 17
**** Housing
***** .5 hour billable.  Worked on issue related to not generating of temp codes for Babcock residents.
**** RCC
***** 2 hour non-billable.  Moved fudd up to Annette Schloss's office.  Moved hard-drives to Machine Room.  Spoke to Jenniffer about swaping phone wall-jacks.
**** HCGS
***** 2.5 hours billable.  Created privileges and add added privilege checking to modules (project, source organism and sample submission).  Updated preview site.
**** HealthyUNH
***** 1 hour billable.  Worked on correcting issues reported by Jo and Stacey.
*** 18
**** Housing
***** 2.5 hours non-billable.  Pre-meeting and meeting on Real-time view of Banner data for RCI Housing app.
**** OCM
***** 3.5 hours non-billable.  Meeting with OCM to discuss outstanding bugs, remaining work for HDWTs and summery work.
*** 19
**** WEEKEND
*** 20
**** WEEKEND
*** 21
**** HOLIDAY
*** 22
**** StaffMeetings
***** 1 hour non-billable.  Weekly Programming Group meeting.
**** OCM
***** 1.5 hour billable.  Added year to calendar tool.  Added student id and incident datetime to various admin-level recordsets.
***** 1.5 hour non-billable.  Fixed bug in 'Find Student' tool when the student's name contains an apostrophe.  Determined the cause of two complaints which were missing their case numbers.
**** Housing
***** 1 hour billable.  Continued worked on accessing ECG database for Housing-Online.  I was able to connect to the database from the housing1.unh.edu.  I reset my password and I can now login.  We'll still need to work on how to access these database from RCC's systems.
*** 23
**** OCM
***** 3 hours non-billable.  Corrected bugs: Loop-hole which allowed complaints to remove their complaints regardless of status.  Changed Complaint form to always save case number, rather than only when it is received.  Changed conduct dashboard to go directly to complaint if the respondent count is 0.  Searching by complaint from conduct dashboard wasn't working.
***** 1 hours billable.  Allow complainants to remove their new complaints.  
**** Housing
***** 1.5 hour billable.  Updated pl/sql functions to resolve issue with 'Babcock Residents should not get temp codes'.  Worked on resolving issues with teams being disbanded on occinfo upload and invited team members being removed from team.
*** 24
**** HealthyUNH
***** 4 hours billable.  Worked on implmentating changes based on meeting from 01/14/2013.
**** Housing
***** 2.5 hour billable.  Updated pl/sql functions to resolve issue with 'Babcock Residents should not get temp codes'.  Worked on resolving issues with teams being disbanded on occinfo upload and invited team members being removed from team.
*** 25
**** Housing
***** 1 hour billable.  Corrected recordset at Blaise's request.
**** OCM
***** 1 hour billable.  Deployed updates to live site.
**** HealthyUNH
***** 1 hour billable.  Deployed updates to live site.
*** 26
**** WEEKEND
*** 27
**** WEEKEND
*** 28
**** OCM
***** 2.5 hour non-billable.  Worked on correcting issues with missing/incorrect complaints view-able for college dean user.
**** NHIHPP
***** .5 hour non-billable.  Emailed NHIHPP with sample reports.
**** Housing
***** 2.5 hour billable.  Updated Column BUILDING_ASSIGNMENT to use correct term.  Dynamically change the page title on in-hall tool.  Updated chosen room report.  Updated temp. elg. code generation.
*** 29
**** OCM
***** .5 hour non-billable.  Continued work on OCM Summer 2013 RFC.
***** 1 hour non-billable.  Updated complaint list and removed view,edit and print buttons for college deans for any complaints they didn't create.
***** .5 hour non-billable.  Fixed incorrect Date on VForms.  
***** 1.5 hour non-billable.  Corrected behavior of Conduct Dashboard seen by Donna Han.
**** Housing
***** 1 hour non-billable.  Fixed incorrect occupancy count in in-hall tool.
**** StaffMeetings
***** 1 hour non-billable.  Weekly Programming Group meeting.
*** 30
**** OCM
***** .5 hour non-billable.  Fixed two bugs Sarah reported.
***** 1 hour non-billable.  Continued work on OCM Summer 2013 RFC.
***** 1.25 hours non-billable.  Testing cloning bug reported by Sarah.
**** RCC
***** .75 hour non-billable.  Worked on merging my three git repos in the housing project (OCM, ResLife, InHall Tool) into a single housing git repo.  The merge work and my commit history for all three projects was retained.
**** HealthyUNH
***** .5 hour non-billable.  Phone call with Stacy to help her with cordinate creation.  Fixed bug with feature modifcation using Firefox.
**** ResLife
***** .5 hour non-billable.  Fixed incorrect application date on return ra application.
**** Housing
***** .5 hour billable.  Tested banner view connection.
**** HCGS
***** 1 hour billable.  Meeting with HCGS.
*** 31
**** HCGS
***** .5 hour billable.  Had cname and db created.
**** OCM
***** 1 hour non-billable.  Fixed bug with cloning v-forms.  When the clone was saved, the sanctions would be disappearing from the parent.
***** 1 hour non-billable.  Determined cause of issue when saving HDW and fixed bug.
***** 1 hour non-billable.  Continued work on OCM Summer 2013 RFC.
**** HealthyUNH
***** 1.5 hours billable.  Worked merging the fitness map into Layout.
**** WJA_AS
***** 1 hour non-billable.  Corrected to determine cause of failure to send forgot password email.
** February
*** 01
**** ePIP
***** .75 hour billable.  Worked with Allan and Angela to upload ePIP data.
**** HealthyUNH
***** .25 hour non-billable.  Fixed problem with loading data on website.
***** 3.5 hour billable.  Reformatted fitness-map page to match site.  Added 'x of y' to feature pop-up.
**** OCM
***** .5 hour non-billable.  Fixed bug with HDW not loading welcome msg step correctly.
**** WJA_AS
***** .5 hour non-billable.  Exchanged emails with customer and determined the cause.
**** WJA_DV
***** .5 hour non-billable.  Responded to email from DV.
*** 02
**** WEEKEND
*** 03
**** WEEKEND
*** 04
**** HCGS
***** 3 hour billable.  Meeting and training sessions with Feseha.  Finished deployment to live site.  Created Google Custom Searches for dev, pre and live.
**** OCM
***** 2.5 hours non-billable.  Determined cause of data lose in HDW.  
**** EMS
***** .5 hour non-billable. Responded to email to events-dev.
**** RCC 
***** 1 hour non-billable.  Entered task for January 2012.
*** 05
**** StaffMeetings
***** 1.5 hours non-billable.  Weekly Programming Group meeting.
**** OCM
***** 2 hours non-billable.  Added display of rendered HTML on step 2.
**** HCGS
***** 1.5 hours billable.  Corrections/Updates based on feedback from 02/04/2013 meeting.
**** RCC
***** 2 hours non-billable.  Moved computers,monitors to new cubicle.
*** 06
**** Housing
***** 2 hour billable.  Deployed to new live.  Corrected bugs.
**** OCM
***** .5 hour non-billable.  Fixed class not being pulled when using 'Find Student'.
***** 1.5 hour non-billable.  Continued work on OCM Summer 2013 RFC.
**** NCEMRR
***** 1.5 hours billable.  Asked for cnames.  Created NCEMRR from MedHome.  Imported into git.
**** ResLife
***** .5 hour non-billable.  Increased the number of points available for off-campus interview.
*** 07
**** StaffMeetings
***** 1 hours non-billable.  Quarterly All Staff Meeting.
**** ePIP
***** .5 hour non-billable.  ePIP Meeting.
**** HealthyUNH
***** 2.25 hours billable.  Implemented new features requested by NHIHPP.
**** OCM
***** .25 hours non-billable.  Fixed bug with incorrect grouping of sanctions in HDW.
**** Housing
***** 2 hours billable.  Implemented new features requested by Blaise.  Worked to determine why it wasn't working for some pidms.
*** 08
**** CURTAILED_OPERATIONS (1 day)
*** 09
**** WEEKEND
*** 10
**** WEEKEND
*** 11
**** Housing
***** 2 hour billable.  
**** ResLife
***** .25 hour non-billable.  Removed duplicate adjectives in RL_WILD_ADJECTIVES.
**** NCEMRR
***** 2 hour non-billable.  Had cnames renamed.  Had databases users created.  Changed references to MEDHOME/MEDHOME2 to NCEMRR.

*** 12
**** StaffMeetings
***** .75 hours non-billable.  Weekly Programming Group meeting.
**** Housing
***** 1.5 hours non-billable.  Merged changes between dev and pre sites.  Pushed updated preview site to live.
**** OCM
***** 1.5 hour billable.  HDW updates.
***** 1 hour non-billable.  Corrections for term semester.  Created new OCM settings field 'current semester code'.
*** 13 
**** Housing
***** 8 hours non-billable.  Fixed/corrected issue with temporary eligibility code.
*** 14
**** NHIHPP 
***** 1 hour non-billable.  Meeting with Chris White to discuss/review the status of resource monitoring project and to additional functionality.
**** ResLife
***** .5 hour non-billable.  Corrected calcuation error in column 'Rec. Score'.
**** OCM
*** 15
**** HealthyUNH
***** .75 hour billable.  Deployed HealtyUNH to live Site!
*** 16
**** WEEKEND
*** 17
**** WEEKEND
*** 18
**** StaffMeetings
***** 1 hour non-billable.  Monthly RCC staff meeting.
**** Housing
***** 1.5 hour non-billable.  Signup
**** OCM
***** 1.5 hour non-billable.  Continued work on OCM Summer 2013 RFC.
*** 19
**** StaffMeetings
***** 1.25 hours non-billable.  Weekly Programming Group meeting.
**** OCM
**** .75 hour non-billable.  Imported missing v-form review columns.
**** 2 hours non-billable.  Finished rough-draft of OCM Summer 2013 RFC.
*** 20
**** OCM
**** 

