* 2012
** July
*** 01
**** WEEKEND
*** 02
**** OCM 
***** 1 hour billable to OCM.  Created 'audit log' based on ApplicationLog from EMS (and functions from EPSCOR).
***** 1 hour billable to OCM.  Added priors and show priors to arrest form.
****  4 hours non-billable to OCM.   Fixes, misc changes.
*** 03
**** OCM
***** 3.5 hours non-billable to OCM.  Meeting with Sarah.
***** 1 hours billable to OCM. I've updated the Complaint Form to include view/update access checks.  In the Application Log, you'll see the results of these checks.
***** 1 hours non-billable to OCM.  Misc. bug fixes.
*** 04
**** HOLIDAY
*** 05
**** VACATION
*** 06
**** VACATION
*** 07
**** WEEKEND
*** 08
**** WEEKEND
*** 09
**** OCM
***** 6 hours non-billable to OCM.  Corrected error loading complaint form.  Added lookup of student info by PIDM using using 'Find Student' tool.  Changed listing of violations/sanctions to honor deprecated column.
*** 10
**** OCM
***** 3 hours non-billable to OCM.  Changed 'members' fields on resolution tab.  Fixed download.  Removed 'hearing to determine' field.  Printing case number and due date on 'student snapshot'
***** 3 hours bilalble to OCM.  Created message areas on dashboads (conduct, arrest, academic).  Imported data from table tcc_tblIncidents to improve lookup of student records.  Import most of the OCM volunteers (most volunteers don't have PIDMs). Switched Res path radioboxes to checkboxes. 
*** 11
**** OCM
**** 3 hours billable to OCM.  Added support for "organization" as the respondent for an complaint form.
**** 1 hours billable to OCM.  Added support for highlighting of dates customizable by OCM.
**** 2 hours non-billable ot OCM. Misc. bug fixes.
