# OCM: 58797
# EMS: 50988
# ePIP: 59333
# Obliterase: 60023
# SpiceCore: 59919
# UACC: 60035
# MedHome: 60036
# Bugzilla: 57720
# HCGS: 60049
# HealthyUNH: 60059
* 2012
** July
*** 01
**** WEEKEND
*** 02
**** OCM 
***** 1 hour billable.  Created 'audit log' based on ApplicationLog from EMS (and functions from EPSCOR).
***** 1 hour billable.  Added priors and show priors to arrest form.
****  4 hours non-billable.   Fixes, misc changes.
*** 03
**** OCM
***** 3.5 hours non-billable.  Meeting with Sarah.
***** 1 hours billable. I've updated the Complaint Form to include view/update access checks.  In the Application Log, you'll see the results of these checks.
***** 1 hours non-billable.  Misc. bug fixes.
*** 04
**** HOLIDAY
*** 05
**** VACATION
*** 06
**** VACATION
*** 07
**** WEEKEND
*** 08
**** WEEKEND
*** 09
**** OCM
***** 6 hours non-billable.  Corrected error loading complaint form.  Added lookup of student info by PIDM using using 'Find Student' tool.  Changed listing of violations/sanctions to honor deprecated column.
*** 10
**** OCM
***** 3 hours non-billable.  Changed 'members' fields on resolution tab.  Fixed download.  Removed 'hearing to determine' field.  Printing case number and due date on 'student snapshot'
***** 3 hours bilalble.  Created message areas on dashboads (conduct, arrest, academic).  Imported data from table tcc_tblIncidents to improve lookup of student records.  Import most of the OCM volunteers (most volunteers don't have PIDMs). Switched Res path radioboxes to checkboxes. 
*** 11
**** OCM
***** 3 hours billable.  Added support for "organization" as the respondent for an complaint form.
***** 1 hour billable.  Added support for highlighting of dates customizable by OCM.
***** 2 hours non-billable ot OCM. Misc. bug fixes.
*** 12
**** OCM
***** 1 hour billable.  Completed work on organizations.
***** 1 hour billable.  Updated Sanction Record to store auto complete (using custom script) sancitons.
***** 1 hour billable.  Updated Sanction Record to store hidden on other - ocm report sanctions.
***** 2.5 hours billable.  Updated perl modules to implement privilege checks to limit access as defined by Sarah.
*** 13 
**** OCM
***** 1.5 hours non-billable. Updated OCM menus to implement privilege checks to limit access.
***** 1.5 hours billable.  Created Arrest Dashboard based on Conudct Dashboard.
***** 1 hour billable.  Update Complaint Form hide/show PIDM/Organization fields based on respondent_type.
***** 1 hour billable.  Added notes/files tab to Arrest Form.  Created Arrest Charges record/recordset.  
*** 14
**** WEEKEND
*** 15
**** WEEKEND
*** 16
**** OCM
***** 2 hours non-billable.  Meet with Yunus Syed to work on allowing OCM to lookup PIDM by Student ID via LDAP.  Created perl function to connect to LDAP and obtain PIDM. 
***** 2 hours non-billable.  Corrected perforcemace problems when using Three Strikes report.'
***** 1 hours non-billable.  Misc bug fixes.
***** 1 hours billable.  Updates to Arrest Form letters.
*** 17
**** OCM
***** 1.5 hours billable. Updates to Arrest Form letters.  Added updating Assoc. Deans to Settings page.
***** 2 hours non-billable.  Continued working on LDAP lookup.  At this point, I switched to using a simple shell script to lookup pidm.
***** 1.5 hours non-billable.  Improved Three Strike report (with Phil's help) to improve loading time and its implemention.
*** 18
**** OCM
***** 6.5 hours non-billable.  Using a script created by Bill Costa from UNHIT, I updated OCM to correctly lookup pidm by student id.  Updated ThreeStrikes, Complaint Form and Arrest Form to use access StudentSnapshot using student_id or org_id.  Updated ConductDashboard & ArrestDashboard to allow search for Organziations using Respondent fields.  
*** 19 
**** OCM
***** 4.5 hour non-billable.  Updated ThreeStrikes, Complaint Form and Arrest Form to improve how they access prior data.  Created Arrast Dashbaord.
***** 1 hour billable.  Created recordset 'Conduct with Scholarship'.
*** 20
**** OCM
***** 3 hours billable.  Created Conduct w/Scholarship - Open Cases recordset.  Created ability for OCM staff to switch to hearing officer.
**** RCI
***** 3 hours non-billable.  Created task-output.py to convert task.org into useable data.
*** 21
**** WEEKEND
*** 22
**** WEEKEND
*** 23
**** RCI
***** 3 hour non-billable.  Finished task-output.py to include billable/non-bibllable total and option hanlding.
**** OCM
***** 1.5 hour billable.  Updated MySanctions report to allow complainant to set completed date.
***** .5 hour billable.  Updated Arrest Form for required/optional fields.
***** .5 hour billable.  Updated Open Sanction Reports to ignore complaints with withdrawn sanctions.
***** .5 hour non-billable.  Updated validate_privilege() to allow specifing AND/OR privilege requirement.
*** 24
**** OCM
***** .5 hour non-billable.  Complted changes to validate_privilege().
***** 2 hour non-billable.  Corrected page loading errors.  Updated OCM Privileges document (will send to Blaise tomorrow.)
**** NHMAPPER (59011)
***** 2.5 hours billable.  Updated PDF files from ODT templates for printable output.
*** 25
**** SIRS (58233)
***** 3.5 hours billable.  Help Al debug problems with UserRecord on SIRS website.
**** OCM 
***** 1 hour billable.  Meeting with OCM, VPSAS and RCI.
***** 2 hours non-billable.  Corrected errors Sarah encountered.  Updated OCM Privileges document.
*** 26
**** OCM
***** .5 hour non-billable.  Updated v_ocm_student_snapshot to correctly include/exclude complaints based on business rules from OCM.
***** 2 hour billable.  Imported OCM Arrest data.
**** NHMAPPER (59011)
***** .5 hour billable.  Minor corrections to PDF files.
**** RCI
***** 2 hour non-billable.  Completed task-output.py.  It now supports including task ids both globally and locally.  The output has been updated to include all projects.
**** EMS
***** .5 hour non-billable. Responded to email to paygate-support.
*** 27
**** OCM
***** .5 hour billable.  Imported OCM Arrest data.
***** 2 hours billable.  Imported OCM Arrest data.
***** 2 hours non-billable.  Updated Arrest/Conduct Dashbaords to include counts for acadmeic years.
***** .5 hour non-billable.  Updated student snapshot to use 'not responsible' column.
**** EMS
***** .5 hour non-billable. Responded to email to paygate-support.
*** 28
**** WEEKEND
*** 29
**** WEEKEND
*** 30
**** OCM
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 31
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
** August
*** 01
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 02
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 03
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 04
**** WEEKEND
*** 05
**** WEEKEND
*** 06
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 07
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 08
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 09
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 10
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 11
**** WEEKEND
*** 12
**** WEEKEND
*** 13
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 14
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 15
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 16
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 17
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 18
**** WEEKEND
*** 19
**** WEEKEND
*** 20
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 21
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 22
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.
*** 23
***** 6 hours non-billable.  QA and testing.  Fixes documented in online Google Doc shared between Sarah and myself.  OCM Deployed!
*** 24
**** VACATION
*** 25
**** WEEKEND
*** 26
**** WEEKEND
*** 27
**** OCM
***** 3 hours non-billable.  Minor corrections based on feedback from Tyler.
*** 28
**** Housing
***** 1 hour non-billable.  Corrected error when uploading student data feed.  
**** OCM
***** 1 hour non-billable.  Corrected error when cloning a complaint report.
**** ePIP
***** 4.5 hours billable.  Spent time researching/testing automated functional testing tools.  In the end I found these tools: http://watir.com/frameworks/, http://watin.org and http://seleniumhq.org.  My suggestion to aew was Selenium.  It provides a browser-based test cause/test suite creation tool and the option to run tests out side of the browser.
*** 29
**** OCM
***** 4.5 hours non-billable.  Corrections to Arrest Form.
**** Housing
***** .5 hours non-billable.  Corrected issue with upload of students data.
*** 30
**** ePIP
***** 3.5 hours billable.  Spent time learning how to create test cases and test suites with Selenium.  
**** OCM
***** 2.5 hours non-billable.  Corrected issue with OCM reported by Sarah.  Worked to determine cause of error with with OptimalQuery on lithium v. OptimalQuery on housing1.
*** 31
**** OCM
***** 2 hours non-billable.  Meeting with Sarah.
***** 1.5 hours billable.  Added status to three strikes report.  Waiting further information from Sarah.
***** .5 billable.  Added new columns to Complaint List.  Violations (Not Responsible, Responsbile, Pending) and Sanctions types.
***** 2 Corrections/bug fixes to OCM.  Sorting in Dean's Report.  Updated Conduct Tool to only show closed cases, responsbile violations, non-responsbile violations and imposed sanctions.
** September
*** 01
**** WEEKEND
*** 02
**** WEEKEND
*** 03
**** HOLIDAY
*** 04
**** OCM
***** 2 hours non-billable.  Corrected error with respondent auto-complete.  Corrected undefined sub-routine errors. 
**** Housing
***** .5 hour non-billable.  Determine cause of missing freshman student data.  (Data wasn't included in last week's update.  Blaise re-uploaded data.)
**** EMS
***** .5 hour non-billable. Responded to email to paygate-support@sr.unh.edu
**** ePIP
***** .5 hour billable.  Meet with Angela to discuss testing.
*** 05
**** OCM
***** 3 hours billable.  Added complainant proxy to OCM_Uploads.  Updated complainant proxy to complaint form.  This field will allow the user to set a proxy for a given complaint form.
**** ePIP
***** 3 hour billable.  Start of testing process.  Time was spent creating accounts.
*** 08
**** WEEKEND
*** 09
**** WEEKEND
*** 10
**** ePIP
***** 6 hours billable.  Continue work on functionality testing.  Wrote script which tranforms Medicaid data from test plan to selenium test cases.
*** 11
**** ePIP
***** 4 hours billable.  Continued work on functionality testing.  Wrote script which tranforms Needy data from test plan to selenium test cases.
**** UACC
***** 1 hour non-billable.  Helped Allan resolve issue with LDAP access from UACC site on housing1.unh.eud.
**** OCM
***** 1 hour billable.  Added new feature to OCM allowing Sarah to set a custom cell phone number for her volunteers.
*** 12
**** Obliterase 
***** 1 hour non-billable.  Meeting with Tucker, Stephen Wood and myself to discuss work for Stephen's company Obliterase.
***** 1 hour billable.  Updated logo and lCreated favicon.ico.  Updated webserver to use management-console.obliterase.com.
**** ePIP
***** 4 hours billable.  Continued work on functionality testing.
*** 13
**** Obliterase 
***** 2 hours billable.  Updated webserver to use cloud-console.obliterase.com.  Most of the changed requested by Steve Wood have been complted (email sent 09/13/2012 02:39 PM).
**** ePIP
***** 4 hours billable.  Continued work on functionality testing.
*** 14
**** Obliterase 
***** 3 hours billable.  Created footer.  Began work on PDF generation.  Made changes to Device Logs recordset.
**** ePIP
***** 3 hours billable.  Continued work on functionality testing.
*** 15
**** WEEKEND
*** 16
**** WEEKEND
*** 17
**** Obliterase 
***** 4 hours billable.  Created Certificate generation.  Sent Steve an update.  Misc. changes to website.
**** ePIP
***** .5 hour billable.  Closed bugs at aew's request.
**** OCM
***** .5 hour non-billable.  Reviewed whether prior is set correctly all AY1213 complaints.  Sent update to Sarah.
*** 18
**** RCC
***** 1.5 hours non-billable.  Installed bugzilla on zathras to test upgrading our Bugzilla
**** OCM
***** 1 hours non-billable correction/bug fixes.
**** Obliterase
***** 1 hours billable.  Corrected Certificate.
*** 19
**** OCM
***** 5 hours billable.  Templates for Hearing Decision.
**** OCM
***** 1 hours non-billable correction/bug fixes.
*** 20
**** OCM
***** 5 hours billable.  Templates for Hearing Decision.
**** ePIP 
***** 1/2 hour billable.  Rebuliding MMIS.
*** 21
**** VACATION
*** 22
**** WEEKEND
*** 23
**** WEEKEND
*** 24
**** VACATION
*** 25 
**** ePIP 
***** 1 hour billable.  Created summaries of security scan report.  Sent to summary to Even.  Sent another to teh,aew and af.
**** OCM
***** 5 hours billable.  Changes to recent police activity report (removed sentence) and add fields (full name, dob, student id and date the letter was created).  Continued work on hearing decision templates. 
*** 26
**** OCM
***** 3 hours non-billable.  Bug fixes to OCM.  Fixed bug to complaint form which made it impossible to add the same sanction with several sanction types.  Updated complaint form to catch invalid 'release of info requested' data.
***** 3 hours billable.  Loading/saving of sanction templates is now working, along with sanction rationale.
*** 27
**** OCM
***** 3.5 hours billable.  Spent time working on enabling ckeditor support for the rationale text-areas; encountered problems.  I'll revisit this next week.
**** Obliterase
***** .5 hour non-billable.  Removed 'cloud' logo.  Removed NEAT from viewLog script.
**** ResLife
***** 1 hour billable.  Minor updates to Job Description page.
*** 28
**** ePIP
***** 2 hours billable.  Testing and verification of data entered and data reported.
**** HCGS
***** 3 hours billable.  Created website; loaded database from medical-home site.  Removed medical home references from HCGS.  The site is now ready.
**** MEDHOME
***** 1 hours billable.  Reviewed MEDHOME website with Allan.  Spent additional time reference website myself.
*** 29
**** WEEKEND
*** 30
**** WEEKEND
** October
*** 01
**** MEDHOME
***** 1 hour non-billable.  Meeting with NHIHPP to discuss the project and moving it forward.
**** Obliterase
***** 1.5 hours billable.  Minor updates to website.  Added images above menu.  Added logo to the left of menu.  Added text above menu.
**** HCGS
***** .5 hours billable.  Deployed website to preview server.
**** SpiceCore
***** 2 hours billable.  Setup website on lithium and myxomatosis.
**** HOURS_OWED
***** 1 HOUR OWED
*** 02
**** OCM
***** 2.5 hours non-billable.  Corrected errors with Recent Police Activity report crashing when filtering on 
**** RCC
***** 1 hours non-billable.  Reset AD password; this was done to access maple.unh.edu account.  Reinstalled MS Office.
**** HealthyUNH
***** 2.5 hours non-billable.  Started working on Healthy Fitness map.
*** 03
**** ResLife
***** 1 hour billable.  Minor updates to Welcome page.
**** ePIP 
***** 1 hour billable.  Training on ePIP upload proceedure.
**** HealthyUNH
***** 4 hours non-billable.  Finished working on Healthly Fitness map.  Using jQuery and a jQuery plug-in, jquery.imagemapster to provide a multi-platform UI.
*** 04
**** RCC
***** 4 hour non-billable.  Downtime due to power outage.  Watching of UNH IT Security training videos.
**** Housing
***** 1.5 hour non-billable.  Meeting with Chris, Blaise, Allan and myself to discuss future Housing work.  Created mock-up of inhall-application page using jdmenu.
**** ResLife
***** .5 hour billable.  Deployed latest changes to live site.
*** 05
**** Housing
***** 1.5 hours non-billable.  Created two other mock-ups using jQuery UI tabs and accordion.  I sent Blaise an email with an update asking him to review them.
**** OCM
***** 1.5 hour non-billable.  Received email from Sarah reporting loss of privileges and cell phone numbers Thursday everything.  After reviewing log and Perl code, I think the problem is related to upload.  I'm waiting on the student feed from back.  Received email from Sarah about incorrect College for student.  After checking database, the issue is incorrect/out-of-day data; emailed Blaise.
**** HealthyUNH
***** 2 hour non-billable.  Minor corrections to map based on feedback from Allan.  Sent email to Stacey and Jo with update.
**** HOURS_OWED
***** 1 HOUR OWED
