* 2012
** July
*** 01
**** WEEKEND
*** 02
**** OCM 
***** 1 hour billable to OCM.  Created 'audit log' based on ApplicationLog from EMS (and functions from EPSCOR).
***** 1 hour billable to OCM.  Added priors and show priors to arrest form.
****  4 hours non-billable to OCM.   Fixes, misc changes.
*** 03
**** OCM
***** 3.5 hours non-billable to OCM.  Meeting with Sarah.
***** 1 hours billable to OCM. I've updated the Complaint Form to include view/update access checks.  In the Application Log, you'll see the results of these checks.
***** 1 hours non-billable to OCM.  Misc. bug fixes.
*** 04
**** HOLIDAY
*** 05
**** VACATION
*** 06
**** VACATION
*** 07
**** WEEKEND
*** 08
**** WEEKEND
*** 09
**** OCM
***** 6 hours non-billable to OCM.  Corrected error loading complaint form.  Added lookup of student info by PIDM using using 'Find Student' tool.  Changed listing of violations/sanctions to honor deprecated column.
*** 10
**** OCM
***** 3 hours non-billable to OCM.  Changed 'members' fields on resolution tab.  Fixed download.  Removed 'hearing to determine' field.  Printing case number and due date on 'student snapshot'
***** 3 hours bilalble to OCM.  Created message areas on dashboads (conduct, arrest, academic).  Imported data from table tcc_tblIncidents to improve lookup of student records.  Import most of the OCM volunteers (most volunteers don't have PIDMs). Switched Res path radioboxes to checkboxes. 
*** 11
**** OCM
***** 3 hours billable to OCM.  Added support for "organization" as the respondent for an complaint form.
***** 1 hour billable to OCM.  Added support for highlighting of dates customizable by OCM.
***** 2 hours non-billable ot OCM. Misc. bug fixes.
*** 12
**** OCM
***** 1 hour billable to OCM.  Completed work on organizations.
***** 1 hour billable to OCM.  Updated Sanction Record to store auto complete (using custom script) sancitons.
***** 1 hour billable to OCM.  Updated Sanction Record to store hidden on other - ocm report sanctions.
***** 2.5 hours billable to OCM.  Updated perl modules to implement privilege checks to limit access as defined by Sarah.
*** 13 
**** OCM
***** 1.5 hours non-billable to OCM. Updated OCM menus to implement privilege checks to limit access.
***** 1.5 hours billable to OCM.  Created Arrest Dashboard based on Conudct Dashboard.
***** 1 hour billable to OCM.  Update Complaint Form hide/show PIDM/Organization fields based on respondent_type.
***** 1 hour billable to OCM.  Added notes/files tab to Arrest Form.  Created Arrest Charges record/recordset.  
*** 14
**** WEEKEND
*** 15
**** WEEKEND
*** 16
**** OCM
***** 2 hours non-billable to OCM.  Meet with Yunus Syed to work on allowing OCM to lookup PIDM by Student ID via LDAP.  Created perl function to connect to LDAP and obtain PIDM. 
***** 2 hours non-billable to OCM.  Corrected perforcemace problems when using Three Strikes report.'
***** 1 hours non-billable to OCM.  Misc bug fixes.
***** 1 hours billable to OCM.  Updates to Arrest Form letters.
*** 17
**** OCM
***** 1.5 hours billable to OCM. Updates to Arrest Form letters.  Added updating Assoc. Deans to Settings page.
***** 2 hours non-billable to OCM.  Continued working on LDAP lookup.  At this point, I switched to using a simple shell script to lookup pidm.
***** 1.5 hours non-billable to OCM.  Improved Three Strike report (with Phil's help) to improve loading time and its implemention.
*** 18
**** OCM
***** 6.5 hours non-billable to OCM.  Using a script created by Bill Costa from UNHIT, I updated OCM to correctly lookup pidm by student id.  Updated ThreeStrikes, Complaint Form and Arrest Form to use access StudentSnapshot using student_id or org_id.  Updated ConductDashboard & ArrestDashboard to allow search for Organziations using Respondent fields.  
*** 19 
**** OCM
***** 4.5 hour non-billable to OCM.  Updated ThreeStrikes, Complaint Form and Arrest Form to improve how they access prior data.  Created Arrast Dashbaord.
***** 1 hour billable to OCM.  Created recordset 'Conduct with Scholarship'.
*** 20
**** OCM
*** 21
**** WEEKEND
*** 22
**** WEEKEND
