# btrfs-convert
# Autogenerated from man page /usr/share/man/man8/btrfs-convert.8.gz
# using Deroffing man parser
complete -c btrfs-convert -s d --description 'disable data checksum.'
complete -c btrfs-convert -s i --description 'ignore xattrs and ACLs.'
complete -c btrfs-convert -s n --description 'disable packing of small files.'
complete -c btrfs-convert -s r --description 'roll back to ext2fs.'

