# btrfs-find-root
# Autogenerated from man page /usr/share/man/man8/btrfs-find-root.8.gz
# using Deroffing man parser
complete -c btrfs-find-root -s g --description 'filter root tree by it\'s original transaction i… [See Man Page]'
complete -c btrfs-find-root -s o --description 'filter root tree by it\'s objectid,tree root\'s o… [See Man Page]'
complete -c btrfs-find-root -s l --description 'filter root tree by B-+ tree\'s level, level 0 in default.'

