# btrfstune
# Autogenerated from man page /usr/share/man/man8/btrfstune.8.gz
# using Deroffing man parser
complete -c btrfstune -s S --description 'updates the seeding value, it forces a fs reado… [See Man Page]'
complete -c btrfstune -s r --description 'enable extended inode refs.'
complete -c btrfstune -s x --description 'enable skinny metadata extent refs.'

