# btrfs-debug-tree
# Autogenerated from man page /usr/share/man/man8/btrfs-debug-tree.8.gz
# using Deroffing man parser
complete -c btrfs-debug-tree -s e --description 'print detailed extents info.'
complete -c btrfs-debug-tree -s d --description 'print info of btrfs device and root tree dirs only.'
complete -c btrfs-debug-tree -s r --description 'print info of roots only.'
complete -c btrfs-debug-tree -s b --description 'print info of the specified block only.'

