# btrfsck
# Autogenerated from man page /usr/share/man/man8/btrfsck.8.gz
# using Deroffing man parser
complete -c btrfsck -s s -l super --description 'specify which superblock copy that you want to use.'
complete -c btrfsck -l repair --description 'try to repair the filesystem.'
complete -c btrfsck -l init-csum-tree --description 'create a new CRC tree.'
complete -c btrfsck -l init-extent-tree --description 'create a new extent tree.'

