# btrfs-show-super
# Autogenerated from man page /usr/share/man/man8/btrfs-show-super.8.gz
# using Deroffing man parser
complete -c btrfs-show-super -s a --description 'print all the superblock information, if this o… [See Man Page]'
complete -c btrfs-show-super -s i --description 'specify which mirror to print out.'

