# btrfs-image
# Autogenerated from man page /usr/share/man/man8/btrfs-image.8.gz
# using Deroffing man parser
complete -c btrfs-image -s r --description 'restore metadump image.'
complete -c btrfs-image -s c --description 'compression level (0 ~ 9).'
complete -c btrfs-image -s t --description 'number of threads (1 ~ 32) to be used to proces… [See Man Page]'
complete -c btrfs-image -s o --description 'use the old restore method, this does not fixup… [See Man Page]'
complete -c btrfs-image -s s --description 'Sanitize the file names when generating the image.'
complete -c btrfs-image -s w --description 'Walk all the trees manually and copy any blocks… [See Man Page]'

