# ctags
# Autogenerated from man page /usr/share/man/man1/ctags.1p.gz
# using Deroffing man parser
complete -c ctags -s a --description 'Append to tagsfile.'
complete -c ctags -s f --description 'Write the object locator lists into tagsfile in… [See Man Page]'
complete -c ctags -s x --description 'Produce a list of object names, the line number… [See Man Page]'
complete -c ctags -s v --description 'If the -v flag is given, an index of the form e… [See Man Page]'

