# cups-browsed
# Autogenerated from man page /usr/share/man/man8/cups-browsed.8.gz
# using Deroffing man parser
complete -c cups-browsed -s v -s d -l debug --description 'Debug mode FILES /etc/cups/cups-browsed.'

