# exempi
# Autogenerated from man page /usr/share/man/man1/exempi.1.gz
# using Deroffing man parser
complete -c exempi -o h: --description '.'
complete -c exempi -o R: --description '.'
complete -c exempi -o x: --description '.'
complete -c exempi -o X: --description '.'
complete -c exempi -o w: -o 's.' -o 'o.' --description '.'
complete -c exempi -s o --description '.'
complete -c exempi -s n --description '.'
complete -c exempi -s g --description '.'
complete -c exempi -s s -s v --description '<files> the files to read from.'

