# gnome-settings-daemon
# Autogenerated from man page /usr/share/man/man1/gnome-settings-daemon.1.gz
# using Deroffing man parser
complete -c gnome-settings-daemon -s h -l help --description 'Prints a short help text and exits.'
complete -c gnome-settings-daemon -l debug --description 'Enables debugging code.'
complete -c gnome-settings-daemon -l timed-exit --description 'Exits after a timeout (30 seconds) for debugging.'

