# gnome-dictionary
# Autogenerated from man page /usr/share/man/man1/gnome-dictionary.1.gz
# using Deroffing man parser
complete -c gnome-dictionary -l look-up --description 'Looks up the specified word using the pre-defin… [See Man Page]'
complete -c gnome-dictionary -l match --description 'Matches one or more words using the pre-defined… [See Man Page]'
complete -c gnome-dictionary -s s -l source --description 'Uses the specified source for looking up words.'
complete -c gnome-dictionary -s D -l database --description 'Use the specified database for looking up words.'
complete -c gnome-dictionary -s S -l strategy --description 'Use the specified strategy for looking up words.'
complete -c gnome-dictionary -l help --description 'Display help information.'

