# grl-inspect
# Autogenerated from man page /usr/share/man/man1/grl-inspect.1.gz
# using Deroffing man parser
complete -c grl-inspect -s h -l help --description 'Show summary of grl-inspect options.'
complete -c grl-inspect -l help-grl --description 'Show summary of Grilo options.'
complete -c grl-inspect -l help-all --description 'Show summary of all options.'
complete -c grl-inspect -s d -l delay --description 'Wait for some seconds before showing results.'
complete -c grl-inspect -s c -l config --description 'Configuration file to use with the plugins.'

