# lightdm-set-defaults
# Autogenerated from man page /usr/share/man/man1/lightdm-set-defaults.1.gz
# using Deroffing man parser
complete -c lightdm-set-defaults -s h -l help --description 'Show help options.'
complete -c lightdm-set-defaults -s k -l keep-old --description 'Only update if no default already set.'
complete -c lightdm-set-defaults -s d -l debug --description 'Enable debugging messages.'
complete -c lightdm-set-defaults -s r -l remove --description 'Remove default value if it\'s the current one.'
complete -c lightdm-set-defaults -s s -l session --description 'Set the default session to SESSION_NAME.'
complete -c lightdm-set-defaults -s g -l greeter --description 'Set the default greeter to GREETER_NAME.'
complete -c lightdm-set-defaults -s a -l autologin --description 'Set the autologin user to USERNAME.'
complete -c lightdm-set-defaults -s i -l hide-users --description 'Set greeter-hide-users to true or false.'
complete -c lightdm-set-defaults -s m -l show-manual-login --description 'Set show-manual-login to true or false.'
complete -c lightdm-set-defaults -s R -l show-remote-login --description 'Set show-manual-login to true or false.'
complete -c lightdm-set-defaults -s l -l allow-guest --description 'Set allow-guest to true or false.  FILES /etc/lightdm/lightdm.'

