# lvmetad
# Autogenerated from man page /usr/share/man/man8/lvmetad.8.gz
# using Deroffing man parser
complete -c lvmetad -s l --description 'Select the type of log messages to generate.'
complete -c lvmetad -s f --description 'Don\'t fork, run in the foreground.'
complete -c lvmetad -s h -s '?' --description 'Show help information.'
complete -c lvmetad -s s --description 'Path to the socket file to use.'
complete -c lvmetad -s V --description 'Display the version of lvmetad daemon.  ENVIRONMENT VARIABLES.'

