# lxc-clone
# Autogenerated from man page /usr/share/man/man1/lxc-clone.1.gz
# using Deroffing man parser
complete -c lxc-clone -l orig --description 'The name of the original container to clone.'
complete -c lxc-clone -l new --description 'The name of the new container to create.'
complete -c lxc-clone -l 'snapshot\\*(T>' --description 'The new container\'s rootfs should be a LVM or b… [See Man Page]'
complete -c lxc-clone -l fssize --description 'In the case of a LVM-backed container, a size f… [See Man Page]'
complete -c lxc-clone -l vgname --description 'For an LVM-backed container, the volume group name to use.'
complete -c lxc-clone -l lvprefix --description 'For an LVM-backed container, a string to prefix… [See Man Page]'
complete -c lxc-clone -s n -s p --description 'be on a logical volume called lxc_c1.'

