# mkfs
# Autogenerated from man page /usr/share/man/man8/mkfs.xfs.8.gz
# using Deroffing man parser
complete -c mkfs -o 'bcdpl.' --description 'A file may be a regular file, a block special f… [See Man Page]'

