# ncmpc
# Autogenerated from man page /usr/share/man/man1/ncmpc.1.gz
# using Type1
complete -c ncmpc -s '?' -l help --description 'Display help.'
complete -c ncmpc -s V -l version --description 'Display version information and build-time configuration.'
complete -c ncmpc -s c -l colors --description 'Enable colors.'
complete -c ncmpc -s C -l no-colors --description 'Disable colors.'
complete -c ncmpc -s m -l mouse --description 'Enable mouse.'
complete -c ncmpc -s M -l no-mouse --description 'Disable mouse.'
complete -c ncmpc -s h -l host --description 'Specify MPD host.'
complete -c ncmpc -s p -l port --description 'Connect to server on PORT.'
complete -c ncmpc -s P -l password --description 'Use password when connecting.'
complete -c ncmpc -s f -l config --description 'Read configuration from file.'
complete -c ncmpc -s k -l key-file --description 'Read key bindings from FILE.'

