# pacaur
# Autogenerated from man page /usr/share/man/man8/pacaur.8.gz
# using Type1
complete -c pacaur -s e -l edit --description 'Edit target(s) \\s-1PKGBUILD\\s0 and view install… [See Man Page]'
complete -c pacaur -s c -l clean --description 'Remove target(s) build files after building target(s).'
complete -c pacaur -s q -l quiet --description 'Show less information for search and query operations.'
complete -c pacaur -s a -l aur --description 'When used with pacman extended operations, only… [See Man Page]'
complete -c pacaur -s r -l repo --description 'When used with pacman extended operations, only… [See Man Page]'
complete -c pacaur -s f -l force --description 'Overwrite existing files when downloading.'
complete -c pacaur -l devel --description 'When used with update operations, also upgrade … [See Man Page]'
complete -c pacaur -l ignore --description 'Ignore a package upgrade.  Can be used more than once.'
complete -c pacaur -l noconfirm --description 'Perform commands without confirmation from the user.'
complete -c pacaur -l noedit --description 'Perform commands without editing any installation files.'
complete -c pacaur -l rebuild --description 'Always rebuild package(s) regardless of any exi… [See Man Page]'
complete -c pacaur -l ignore-ood --description 'When searching the \\s-1AUR,\\s0 ignore all resul… [See Man Page]'
complete -c pacaur -l no-ignore-ood --description 'When searching the \\s-1AUR,\\s0 also show result… [See Man Page]'
complete -c pacaur -l votes --description 'When searching the \\s-1AUR,\\s0 sort the results… [See Man Page]'
complete -c pacaur -l insecure --description 'When using the secure mode, temporarily enable … [See Man Page]'

