# pcsc-spy
# Autogenerated from man page /usr/share/man/man1/pcsc-spy.1.gz
# using Type1
complete -c pcsc-spy -s d -l diffable --description 'Demove the variable parts (like handler values)… [See Man Page]'
complete -c pcsc-spy -s h -l help --description 'Display a short help text.'
complete -c pcsc-spy -s n -l nocolor --description 'Disable the output colorization (if you want re… [See Man Page]'

