# qmi-network
# Autogenerated from man page /usr/share/man/man1/qmi-network.1.gz
# using Deroffing man parser
complete -c qmi-network -l help --description 'Show help options.'
complete -c qmi-network -l version --description 'Show version COPYRIGHT Copyright (2013) Aleksan… [See Man Page]'

