# snapper
# Autogenerated from man page /usr/share/man/man8/snapper.8.gz
# using Deroffing man parser
complete -c snapper -s q -l quiet --description '.'
complete -c snapper -s v -l verbose --description '.'
complete -c snapper -s t -l table-style --description '.'
complete -c snapper -s c -l config --description '.'
complete -c snapper -l no-dbus --description '.'
complete -c snapper -l version --description '.'
complete -c snapper -s f -l fstype --description '.'
complete -c snapper -l template --description '.'
complete -c snapper -l type --description '.'
complete -c snapper -l pre-number --description '.'
complete -c snapper -s p -l print-number --description '.'
complete -c snapper -s d -l description --description '.'
complete -c snapper -l cleanup-algorithm --description '.'
complete -c snapper -s u -l userdata --description '.'
complete -c snapper -l command --description '.'
complete -c snapper -s o -l output --description '.'
complete -c snapper -s i -l input --description '.'
complete -c snapper -o ':user.bar' --description 'for removed attributes oc o 2. 3.'
complete -c snapper -o '+:security.selinux' --description 'for modified attributes PERMISSIONS.'

