# testparm
# Autogenerated from man page /usr/share/man/man1/testparm.1.gz
# using Deroffing man parser
complete -c testparm -s s --description 'Without this option, testparm will prompt for a… [See Man Page]'
complete -c testparm -s '?' -l help --description 'Print a summary of command line options.'
complete -c testparm -s V -l version --description 'Prints the program version number.'
complete -c testparm -s v --description 'If this option is specified, testparm will also… [See Man Page]'
complete -c testparm -s t --description 'Output data in specified encoding.'
complete -c testparm -l parameter-name --description 'Dumps the named parameter.'
complete -c testparm -l section-name --description 'Dumps the named section.'

