# tracker-extract
# Autogenerated from man page /usr/share/man/man1/tracker-extract.1.gz
# using Deroffing man parser
complete -c tracker-extract -s '?' -l help --description 'Show summary of options.'
complete -c tracker-extract -s v -l verbosity --description 'Set verbosity to N.  This overrides the config value.'
complete -c tracker-extract -s f -l file --description 'The FILE to extract metadata from.'
complete -c tracker-extract -s m -l mime --description 'The MIME type to use for the file.'
complete -c tracker-extract -s d -l disable-shutdown --description 'Disable shutting down after 30 seconds of inactivity.'
complete -c tracker-extract -s i -l force-internal-extractors --description 'Use this option to force internal extractors ov… [See Man Page]'
complete -c tracker-extract -l force-module --description 'Force a particular module to be used.'
complete -c tracker-extract -s V -l version --description 'Show binary version.'

