# tracker-writeback
# Autogenerated from man page /usr/share/man/man1/tracker-writeback.1.gz
# using Deroffing man parser
complete -c tracker-writeback -s '?' -l help --description 'Show summary of options.'
complete -c tracker-writeback -s V -l version --description 'Returns the version of this binary.'
complete -c tracker-writeback -s v -l verbosity --description 'Sets the logging level, 0=errors, 1=minimal, 2=… [See Man Page]'
complete -c tracker-writeback -s d -l disable-shutdown --description 'Disable shutting down after 30 seconds of inactivity.'

