# tracker-tag
# Autogenerated from man page /usr/share/man/man1/tracker-tag.1.gz
# using Deroffing man parser
complete -c tracker-tag -s '?' -l help --description 'Show summary of options.'
complete -c tracker-tag -s l -l limit --description 'Limit search to N results.  The default is 512.'
complete -c tracker-tag -s o -l offset --description 'Offset the search results by N.'
complete -c tracker-tag -s r -l or-operator --description 'Use OR for search terms instead of AND (the default).'
complete -c tracker-tag -s t -l list --description 'List all tags.'
complete -c tracker-tag -s s -l show-files --description 'Show the files associated with each tag.'
complete -c tracker-tag -s a -l add --description 'Add a tag with the name TAG.'
complete -c tracker-tag -s d -l delete --description 'Delete a tag with the name TAG.'
complete -c tracker-tag -s e -l description --description 'This option ONLY applies when using  --add and … [See Man Page]'
complete -c tracker-tag -s V -l version --description 'Print version.'

