# tracker-stats
# Autogenerated from man page /usr/share/man/man1/tracker-stats.1.gz
# using Deroffing man parser
complete -c tracker-stats -s '?' -l help --description 'Show a brief help message.'
complete -c tracker-stats -s V -l version --description 'Print version.'

