# tracker-sparql
# Autogenerated from man page /usr/share/man/man1/tracker-sparql.1.gz
# using Deroffing man parser
complete -c tracker-sparql -s '?' -l help --description 'Show summary of options.'
complete -c tracker-sparql -s f -l file --description 'Use a FILE with SPARQL content to query or update.'
complete -c tracker-sparql -s q -l query --description 'Use a SPARQL string to query the database with.'
complete -c tracker-sparql -s u -l update --description 'This has to be used with   --query.'
complete -c tracker-sparql -s c -l list-classes --description 'Returns a list of classes which describe the on… [See Man Page]'
complete -c tracker-sparql -s x -l list-class-prefixes --description 'Returns a list of classes and their related prefixes.'
complete -c tracker-sparql -s p -l list-properties --description 'Returns a list of properties which pertain to a class.'
complete -c tracker-sparql -s n -l list-notifies --description 'Returns a list of classes which are notified ov… [See Man Page]'
complete -c tracker-sparql -s i -l list-indexes --description 'Returns a list of properties which are indexed in the database.'
complete -c tracker-sparql -s s -l search --description 'Returns a list of classes and properties which … [See Man Page]'
complete -c tracker-sparql -l 'query.' --description 'This tells tracker-sparql to use the SPARQL upd… [See Man Page]'
complete -c tracker-sparql -s V -l version --description 'Print version.'

