# tracker-import
# Autogenerated from man page /usr/share/man/man1/tracker-import.1.gz
# using Deroffing man parser
complete -c tracker-import -s '?' -l help --description 'Show summary of options.'
complete -c tracker-import -s V -l version --description 'Print version.'

