# tracker-miner-fs
# Autogenerated from man page /usr/share/man/man1/tracker-miner-fs.1.gz
# using Deroffing man parser
complete -c tracker-miner-fs -s '?' -l help --description 'Show summary of options.'
complete -c tracker-miner-fs -s V -l version --description 'Returns the version of this binary.'
complete -c tracker-miner-fs -s v -l verbosity --description 'Sets the logging level, 0=errors, 1=minimal, 2=… [See Man Page]'
complete -c tracker-miner-fs -s s -l initial-sleep --description 'Sets the initial sleep time before crawling the… [See Man Page]'
complete -c tracker-miner-fs -s n -l no-daemon --description 'Tells the miner to exit once all indexing has f… [See Man Page]'
complete -c tracker-miner-fs -s e -l eligible --description 'Checks if   FILE  is eligible for being mined b… [See Man Page]'
complete -c tracker-miner-fs -s d -l disable-miner --description 'Tells the daemon to disable the in-house miners it supports.'

