# tracker-info
# Autogenerated from man page /usr/share/man/man1/tracker-info.1.gz
# using Deroffing man parser
complete -c tracker-info -s '?' -l help --description 'Show summary of options.'
complete -c tracker-info -s V -l version --description 'Print version.'
complete -c tracker-info -s f -l full-namespaces --description 'By default, all keys and values reported about … [See Man Page]'
complete -c tracker-info -s c -l plain-text-content --description 'If the resource being displayed has nie:PlainTextContent (i. e.'
complete -c tracker-info -s t -l turtle --description 'Output results as Turtle RDF.'

