# vimpc
# Autogenerated from man page /usr/share/man/man1/vimpc.1.gz
# using Deroffing man parser
complete -c vimpc -s v -l version --description 'Print the version of vimpc.'
complete -c vimpc -s h -l host --description 'Connect to a running MPD instance on  hostname … [See Man Page]'
complete -c vimpc -s p -l port --description 'Use port to connect to mpd ENVIRONMENT VARIABLE… [See Man Page]'

