# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# https://clauswitt.com/customizing-the-zsh-prompt-with-oh-my-zsh-themes.html
ZSH_THEME="clauswitt"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(autojump colorize colored-man copydir copyfile cp git git-extras
         git-flow github git-hubflow git-remote-branch gnu-utils history
         command-not-found python ruby history-substring-search
         rvm ssh-agent themes)

source $ZSH/oh-my-zsh.sh

source $HOME/.zsh/nonlogin.d/00init
source $HOME/.zsh/nonlogin.d/10history
source $HOME/.zsh/nonlogin.d/20prompt
source $HOME/.zsh/nonlogin.d/30path
source $HOME/.zsh/nonlogin.d/40editor
source $HOME/.zsh/nonlogin.d/80functions
source $HOME/.zsh/nonlogin.d/90aliases
source $HOME/.zsh/nonlogin.d/99misc
