(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector ["black" "#d55e00" "#009e73" "#f8ec59" "#0072b2" "#cc79a7" "#56b4e9" "white"])
 '(auto-insert-mode t)
 '(auto-revert-interval 1)
 '(background-color "#fdf6e3")
 '(background-mode light)
 '(blink-cursor-mode nil)
 '(bmkp-last-as-first-bookmark-file "~/.emacs.d/bookmarks")
 '(bookmark-save-flag t)
 '(browse-url-browser-function (quote browse-url-generic))
 '(browse-url-generic-program "/opt/google/chrome/google-chrome")
 '(c-default-style (quote ((c-mode . "k&r") (c++-mode . "k&r") (java-mode . "java") (awk-mode . "awk"))))
 '(column-number-mode t)
 '(cursor-color "#657b83")
 '(desktop-path (quote ("~/.emacs.d/.cache/")))
 '(display-time-mode t)
 '(emeteo-timeout 10)
 '(fci-rule-character-color "#1c1c1c")
 '(fci-rule-color "#1c1c1c")
 '(flymake-gui-warnings-enabled nil)
 '(flymake-log-level 0)
 '(flymake-no-changes-timeout 0.5)
 '(flymake-perlcritic-severity 1)
 '(font-use-system-font nil)
 '(foreground-color "#657b83")
 '(highlight-changes-colors (quote ("#d33682" "#6c71c4")))
 '(highlight-tail-colors (quote (("#073642" . 0) ("#546E00" . 20) ("#00736F" . 30) ("#00629D" . 50) ("#7B6000" . 60) ("#8B2C02" . 70) ("#93115C" . 85) ("#073642" . 100))))
 '(icicle-mode t)
 '(inhibit-startup-screen t)
 '(ispell-personal-dictionary "~/.emacs.d/aspell.dict")
 '(message-citation-line-format "On %a, %b %d %Y at %R, %N wrote:
")
 '(message-citation-line-function (quote message-insert-formatted-citation-line))
 '(message-cite-style nil)
 '(mk-proj-ack-cmd "~/bin/ack")
 '(mu4e-view-prefer-html t)
 '(nxml-child-indent 4)
 '(nxml-outline-child-indent 2)
 '(offlineimap-command "offlineimap -u machineui")
 '(printer-name "HP_Color_LaserJet_3800")
 '(quack-global-menu-p nil)
 '(regex-tool-backend (quote perl))
 '(scroll-bar-mode nil)
 '(send-mail-function (quote sendmail-send-it))
 '(sgml-basic-offset 4)
 '(show-paren-mode t)
 '(size-indication-mode t)
 '(sql-product (quote oracle))
 '(sql-sqlite-program "sqlite3")
 '(sqlplus-command "/home/skk/bin/sqlplus.sh")
 '(tab-always-indent nil)
 '(term-unbind-key-list (quote ("C-x" "C-c" "C-h" "C-y" "<ESC>")))
 '(tool-bar-mode nil)
 '(tramp-default-method "ssh"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "Anonymous Pro" :foundry "unknown" :slant normal :weight normal :height 99 :width normal))))
 '(which-func ((t (:inherit mode-line)))))
