(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector ["black" "#d55e00" "#009e73" "#f8ec59" "#0072b2" "#cc79a7" "#56b4e9" "white"])
 '(auto-insert-mode t)
 '(auto-revert-interval 1)
 '(background-color "#fdf6e3")
 '(background-mode light)
 '(bmkp-last-as-first-bookmark-file "~/.emacs.d/bookmarks")
 '(bookmark-save-flag t)
 '(browse-url-browser-function (quote browse-url-generic))
 '(browse-url-generic-program "/opt/google/chrome/google-chrome")
 '(c-default-style (quote ((c-mode . "k&r") (c++-mode . "k&r") (java-mode . "java") (awk-mode . "awk"))))
 '(column-number-mode t)
 '(cursor-color "#657b83")
 '(custom-enabled-themes (quote (tango-dark)))
 '(custom-safe-themes (quote ("1e1f299f8f536d13a8e47be55a46d24be5715ef2ea38ecd7b4e509deb199e706" "4aafea32abe07a9658d20aadcae066e9c7a53f8e3dfbd18d8fa0b26c24f9082c" "36afe64261e1de73fcfadedf154e4bc2c9ec1969bde0c21798d31366897bc4d2" "a7816e280688829bde537faf2a1ec736d383ce6d97e39e1439d65d153143c2fa" "d6a00ef5e53adf9b6fe417d2b4404895f26210c52bb8716971be106550cea257" "7fe1e3de3e04afc43f9a3d3a8d38cd0a0efd9d4c" "d14db41612953d22506af16ef7a23c4d112150e5" default)))
 '(custom-theme-load-path (quote ("/home/skk/.emacs.d/el-get/" custom-theme-directory t "~/.emacs.d/themes" "~/.emacs.d/el-get/theme-sinburn")))
 '(desktop-path (quote ("~/.emacs.d/.cache/")))
 '(display-time-mode t)
 '(emeteo-timeout 10)
 '(fci-rule-character-color "#1c1c1c")
 '(fci-rule-color "#1c1c1c")
 '(flymake-gui-warnings-enabled nil)
 '(flymake-log-level 0)
 '(flymake-no-changes-timeout 0.5)
 '(flymake-perlcritic-severity 1)
 '(foreground-color "#657b83")
 '(icicle-mode t)
 '(inhibit-startup-screen t)
 '(ispell-personal-dictionary "~/.emacs.d/aspell.dict")
 '(message-citation-line-format "On %a, %b %d %Y at %R, %N wrote:
")
 '(message-citation-line-function (quote message-insert-formatted-citation-line))
 '(message-cite-style nil)
 '(mk-proj-ack-cmd "~/bin/ack")
 '(mu4e-view-prefer-html t)
 '(nxml-child-indent 4)
 '(nxml-outline-child-indent 2)
 '(offlineimap-command "offlineimap -u machineui")
 '(printer-name "HP_Color_LaserJet_3800")
 '(regex-tool-backend (quote perl))
 '(scroll-bar-mode nil)
 '(send-mail-function (quote sendmail-send-it))
 '(sgml-basic-offset 4)
 '(show-paren-mode t)
 '(size-indication-mode t)
 '(sql-product (quote oracle))
 '(sql-sqlite-program "sqlite3")
 '(sqlplus-command "/home/skk/bin/sqlplus.sh")
 '(tab-always-indent nil)
 '(term-unbind-key-list (quote ("C-x" "C-c" "C-h" "C-y" "<ESC>")))
 '(tool-bar-mode nil)
 '(tramp-default-method "ssh"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(which-func ((t (:foreground "blue")))))
