# -*- mode: shell-script -*-

# ~/.bash_profile is executed by bash(1) for login shells.

if [[ "$TERM" == "dumb" ]]; then
    export PS1=""
    unset prompt_command
    exit 0
fi

# source all login.d files
source ~/.bash/_utils
source-dir ~/.bash/login.d
