# -*- mode: shell-script -*-

source ~/.bash/_utils
source-dir ~/.bash/nonlogin.d

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
