# -*- mode: shell-script -*-

[[ -f /etc/profile ]] && source /etc/profile

source ~/.bash/_utils
source-dir ~/.bash/nonlogin.d

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting


[[ -r $rvm_path/scripts/completion ]] && . $rvm_path/scripts/completion

