# ~/.bashrc is executed by zsh(1) for non-login shells.

# source all nonlogin.d files
source ~/.bash/_utils

if [[ "$TERM" == "dumb" ]]; then
    export PS1=""
    unset prompt_command
    exit 1
fi

source-dir ~/.bash/nonlogin.d
