source "http://rubygems.org"

# Add dependencies to develop your gem here.
# Include everything needed to run rake, tests, features, etc.
group :development do
  gem "shoulda", ">= 0"
  gem "rdoc", "~> 3.12"
  gem "bundler", "~> 1.0"
  gem "jeweler", "~> 1.8.7"
  gem "simplecov", "~> 0.8.2"
  gem "simplecov-rcov", "~> 0.2.0"
  gem 'mixlib-cli', "~> 1.3.0"
  gem 'mixlib-log', "~> 1.6.0"
  gem 'rubocop', "~> 0.15.0"
end
